# ~/.config/fish/config.fish

# Generic
set fish_greeting (fortune)

# Face
# use 256 color term
if begin; status --is-interactive; end
    set -gx TERM xterm-256color
end

# Functions and Alias
alias md='mkdir -p'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
# alias r='ranger'

# for esp-idf, esp32 etc.
alias get_idf='source $HOME/espressif/esp-idf-v5.4.1/export.fish'

function l
    ll -ah --color=always $argv | less -R
end

# cli editors
# alias e='emacs'
alias v='nvim'
alias n='nvim-qt'
# alias h='helix'

# Python
alias py='ipython'
alias pn='jupyter notebook' # lab
alias pi='pip install -i https://pypi.tuna.tsinghua.edu.cn/simple'
# alias piu='sudo pip install --upgrade'
# alias jns='jupyter notebook --no-browser --port=9999' # server
# alias jnc='ssh -N -f -L localhost:8888:localhost:9999 me@10.110.1.xx'  # fill real addr here!  TODO
## - run jps on the sever, and copy the URL the sever given
## - run jpc on the client, enter the server psw nowhere
## - paste the server URL into a client web browser, change 9999 to 8888, and visit the new URL page

# Git
alias ga='git add -A'
alias gc='git clone' # the mirror version is better for github! this is also useful, esp. for gitlab etc.
alias gd='git diff'
alias gl='git log'
alias gm='git commit -m'
alias gs='git status'

# add, commit, push
function gamp
    git add -A; git commit -m $argv; git push
end

# git clone mirror
function gcm
    git clone 'https://github.com.cnpmjs.org/'$argv[1]
end

# Local configuration
if test -r ~/.config/fish/local.fish
    . "~/.config/fish/local.fish"
end

export TERMINFO=/usr/share/terminfo

# copied from $FISH_CONFIG/functions/br.fish
# This script was automatically generated by the broot program.
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command it produces, if any.
# It's needed because some shell commands, like `cd`, have no useful effect if executed in a subshell.
function br --wraps=broot
    set -l cmd_file (mktemp)
    if broot --outcmd $cmd_file $argv
        read --local --null cmd < $cmd_file
        rm -f $cmd_file
        eval $cmd
    else
        set -l code $status
        rm -f $cmd_file
        return $code
    end
end

function fish_prompt -d "Write out the prompt"
    # 这显示为 USER@HOST 09.11 12:30:45 /home/user/ >，带有颜色
    printf '\n %s%s%s@%s%s%s %s%s%s %s%s%s > ' \
    (set_color $fish_color_user) (whoami) (set_color normal) \
    (set_color $fish_color_quote) (hostname) (set_color normal) \
    (set_color $fish_color_match) (date "+%y.%m.%d %H.%M.%S") (set_color normal) \
    (set_color $fish_color_cwd) (prompt_pwd) (set_color normal)
end

# To print the current date in my calendar
# python ~/.ipython/profile_default/startup/50_init.py
echo

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if test -f /opt/miniconda3/bin/conda
    eval /opt/miniconda3/bin/conda "shell.fish" "hook" $argv | source
else
    if test -f "/opt/miniconda3/etc/fish/conf.d/conda.fish"
        . "/opt/miniconda3/etc/fish/conf.d/conda.fish"
    else
        set -x PATH "/opt/miniconda3/bin" $PATH
    end
end
# <<< conda initialize <<<

# 告诉系统，我们的Zephyr SDK工具箱在哪里
# set -gx ZEPHYR_SDK_DIR /home/truth/zephyr-tools/zephyr-sdk-0.16.1
set -gx ZEPHYR_SDK_INSTALL_DIR /home/truth/zephyr-tools/zephyr-sdk-0.16.1

# 告诉系统，我们使用的是Zephyr自家的工具链
set -gx ZEPHYR_TOOLCHAIN_VARIANT zephyr

# 告诉系统，Zephyr的基础源码在哪里（west update成功后才会存在）
# set -gx ZEPHYR_BASE /home/truth/ncs/zephyr
# set -gx ZEPHYR_BASE /home/truth/ncs/sdk-nrf/zephyr
